---
title: "COVID eBirding: Preliminary analyses"
output: html_document
date: "2021/10/28"
author: "Karthik Thrikkadeeri"
---

This is the preliminary analysis notebook for the COVID eBirding study.
Here, I explore mainly via visualisations the basic patterns in the data.
Our question is how the pandemic has affected birdwatching as well as birds in India.

```{r data_filt, eval=FALSE, echo=FALSE}
### importing from raw ebd
load("data/ebd_IN_relSep-2021.RData") # 2 mins!
data <- data %>% filter(YEAR >= 2018) # 20 secs!
save.image("data/rawdata.RData") # 3 mins
# load("data/rawdata.RData")

### filters
groupaccs <- read.csv("data/ebd_users_GA_relSep-2021.csv", na.strings = c(""," ",NA),
                        quote = "", header = T, nrows = 401)  # excluding empty cells

groupaccs <- groupaccs %>% 
  mutate(CATEGORY = case_when(GA.1 == 1 ~ "GA.1", GA.2 == 1 ~ "GA.2", TRUE ~ "NG"))

filtGA <- groupaccs %>% filter(CATEGORY == "GA.1") %>% select(OBSERVER.ID)

data0 <- data %>% anti_join(filtGA) %>% filter(PROTOCOL.TYPE %in% c("Traveling","Stationary"))

rm(list = setdiff(ls(envir = .GlobalEnv), c("data0")), pos = ".GlobalEnv")
save.image("data/data0.RData")

# random subset for analysis
set.seed(10)
data_sub <- data0 %>% filter(GROUP.ID %in% sample(unique(data0$GROUP.ID),100000))
save(data_sub, file = "data/data_sub.RData")
```

```{r data_load, cache=TRUE, include=FALSE}
load("data/data_sub.RData")
```

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
```





