---
title: "Birding in the time of COVID: Pandemic effects illuminated by birdwatchers, and implications for citizen science inference"
author: "Karthik Thrikkadeeri, Ashwin Viswanathan"
bibliography: covid-ebirding.json
csl: ibis.csl
link-citations: yes
output: 
  word_document:
    number_sections: true
    reference_docx: rmd_word_template.docx
---

<!-- <style> -->

<!-- body { -->

<!-- text-align: justify} -->

<!-- </style> -->

Alternative titles:

Birding in the time of COVID: Context-dependence of pandemic effects on birdwatching and birds, and importance of scale considerations

Pandemic-induced changes in birdwatcher behaviour outweighed by lack of corresponding decline in data quantity and of directional change in bird responses

# Abstract

While citizen science offers several advantages over traditional methods of systematic data collection, the unstructured nature of citizen science data also presents several challenges. True large-scale patterns of natural processes can be confounded and overshadowed by artefactual patterns resulting from changes in behaviour of the observers and therefore the nature of the collected data itself. Since the utility of such data is thus contingent on human circumstance, we wanted to ascertain how one such citizen science programme, eBird, was impacted by the deadliest global pandemic of the 21st century. To understand whether eBird data from the pandemic years in India was useful and reasonably interpretable in and of itself, and whether the nature of this data was different from that of preceding years, we explored several metrics of data quantity and quality. We also compared patterns of bird species reporting between the different years. We found no negative impact of the pandemic on data quantity, but data quality changed in certain expected ways during the peak periods involving lockdowns, mainly due to decreased human mobility and social interaction. Importantly, we did not find a direct impact of the changes in birder behaviour on large-scale patterns of bird species reporting, despite high degrees of variability and contradiction at finer scales. Moreover, there was no clear evidence of shifts in bird abundance or behaviour due to the pandemic. Our results show that birdwatchers as data collectors are resilient to disturbance, and that the effects of the pandemic on birding and birds are highly context- and scale- dependent. In summary, eBird data in India from the pandemic years remains useful and interpretable for most large-scale applications, but will benefit from preliminary data quality checks when applied to fine-scale questions.

# Introduction

## Birds and citizen science

Citizen science (CS) today is a research technique that engages volunteers from the general public---most of whom are not trained as scientists---in collecting and/or analysing and interpreting data as part of a scientific enquiry [@silvertown2009]. Importantly, CS programmes facilitate attempts at answering large-scale questions that are otherwise not feasible [@macphail2020]. CS projects have been around for several decades [see @miller-rushing2012], and some large-scale bird monitoring programmes designed to better understand bird ecology and inform conservation have involved volunteer birdwatchers as data collectors [e.g., @greenwood1995; @praveen2022].

Today, CS programmes related to ecology or the environment vary widely in terms of methodological approach and complexity of data collected [@pocock2017]. In fact, the majority of ecological CS projects are characterised by unstructured data collection protocols [@pocock2017]. For example, iNaturalist collects observations of opportunistic species detections, with minimal information on the sampling process [@dicecco2021].

Birdwatching (hereafter birding) is a nature-based activity that is enjoyed by people from a wide variety of backgrounds, and birders frequently make "checklists" of the bird species they observe in different birding sessions, often with accurate counts. By volunteering the data that is thus inherently collected during participation in the activity, numerous birders---from trained researchers to experienced birders to laypersons---are able to contribute to the scientific study of birds. eBird [@sullivan2014] is one such CS project that gathers and stores data from birders all over the world, enabling large-scale robust scientific analysis and output [@kelling2019].

## eBird: pros and cons \~

eBird data has proved very useful in better understanding the ecology of birds, species ranges [e.g., @sreekumar2021; @sinnott2021], migration [e.g., @aoki2021; @youngflesh2021], behaviour [e.g., @alaniz2020; @winger2019], morphology [e.g., @menon2022; @vrettos2021] and conservation action [@sullivan2017; @soib2020; @ruiz-gutierrez2021]. (See `Patankar et al. in press` for a list of scientific outputs using eBird from India.)

Although the openness, inclusivity, size and scale of CS programmes like eBird often compensate for the logistical, bureaucratic and practical challenges of traditional data collection protocols, a major shortcoming is the fundamental unsystematic nature of CS data [see @pocock2017]. As the observers decide when, where and for how long to make observations, the sampling processes are bound to vary temporally as well as spatially. There are data quality standards that CS projects need to meet in order to improve the inherent value of their datasets. Any robust large-scale analysis of distributions or abundance trends requires the sampling processes across space and time in the data being analysed to be comparable to a certain extent.

In the case of "semi-structured" datasets like that of eBird [@kelling2019], including some of the effort metadata as covariates in the analytical framework can account for false negatives [@johnston2021]. However, this solution breaks down when the effort itself is highly incomparable across the scales of interest. Subsampling across space and time can also help to some degree [@johnston2021], but this greatly reduces the overall size of the dataset. Therefore, in order to effectively utilise the size and scale of CS datasets, the nature of the data (i.a., spatial and temporal spread or coverage, observer effort, species reporting bias) needs to be comparable across space and time.

## COVID-19: the wrench in the works

The COVID-19 pandemic poses a big challenge for CS programmes in this respect [@hochachka2021]. COVID-19 is a deadly infectious disease that resulted in a widespread pandemic. It was the deadliest pandemic of the 21st century and one of the deadliest in human history, with a death toll of more than 5.5 million (around 0.07% of the global population; Worldometer [-@worldometer2022]; Wikipedia [-@wikipedia2022]), alongside others like the bubonic plague, influenza, smallpox and even cholera. Unsurprisingly, governments across the world had taken various precautionary and preventive measures, and had implemented various restrictions such as nation- or state-wide lockdowns and curfews, quarantines and self-isolation, and shutting down of non-essential public services and activities [see @hale2020].

The direct distress of the pandemic, together with the various preventive measures implemented to control it, has had severe impacts on general health and well-being of the public---on not just physical but also psychological and social facets [@li2020; @vanbavel2020]. Therefore, the characteristics of the data collected in CS projects are likely to have changed substantially. Indeed, some CS projects had decreased participation and thus lower data quantity owing to various physical and travel restrictions [@kishimoto2021], and birder behaviour has been shown to have changed in spatial, temporal, social, demographic and nation-linked aspects of birding [@randler2020]. Restricted mobility has resulted in changes to spatial coverage and evenness of data, with observations being concentrated in urbanised locations [@vardi2021], thus reducing its overall informational value [@zhang2020]. The overall diversity of habitats surveyed has also decreased [@hochachka2021].

However, there are also arguments for the other side. It is well-known that leisure and recreation activities play a vital role in improving physical and mental health [@weng2014], and that outdoor activities such as birdwatching are better for restoring attention than indoor activities [@weng2014]. The pandemic required people to actively monitor and improve their health [see @li2020; @vanbavel2020] and brought an increased desire in people to connect with the natural world [e.g., @marsh2021]. Many turned to birding as their activity of choice [@randler2020], and there was even active promotion and encouragement of nature-related activities such as birding [e.g., @birdcountindia2020]. All this suggests the possibility of increased data generation during the pandemic, as has been found to be the case with the citizen science programme iNaturalist [@basile2021].

Moreover, the pandemic restrictions could have reduced the tendency for birders to "flock" to birding hotspots (irrespective of the urban-rural dichotomy), and instead forced them to upload observations from around their erstwhile under-surveyed neighbourhoods, resulting in less clustering [@kishimoto2021]. @hochachka2021 found that alteration in birder behaviour during the month-long lockdown, while present, was not as substantial as expected from the magnitude of change to daily life, and that biases were seen mostly in habitat representation and observer effort. They also found high variability in patterns across the four political units they studied, thus emphasising the importance of regional differences and nuances. Additionally, most studies exploring the impacts of the pandemic [e.g., @hochachka2021] have failed to assess the impacts at broader temporal scales of relevance for large-scale analyses of abundance trends.

For instance, the State of India's Birds 2020 report [@soib2020] was a comprehensive national-level assessment of range, abundance trends and conservation status for 800+ Indian bird species, using more than 10 million observations uploaded by over 15,500 birders to eBird. The Sarus Crane, Vulnerable on the IUCN Global Red List, was shown to have moderate declines in both long-term and short-term trends. However, some of the behavioural changes in birders during the pandemic such as reduced mobility and increased urban dominance of observations could have directly led to lower detections of this species. As a result, this would then cause the trends for these years to be much lower than they actually are. As such assessments of abundance trends and distributions have serious implications in informing conservation policy, their robust needs to be ensured.

In these unprecedented and disruptive times, systematic monitoring programmes following traditional protocols---which are especially contingent on human circumstances---have been brought to a halt, and their pitfalls have become obvious. However, many of these shortcomings do not apply as strongly to (and hence can be overcome by using) large-scale, crowdsourced, open access data, such as from CS programmes [@bates2020], many of which have continued to operate. Moreover, data from the pandemic, arriving amidst this latest period of intense and extremely rapid expansion of human activity (and thereby modification of the environment), also offers an invaluable opportunity to study questions relating to the influence of anthropogenic factors on organisms [@rutz2020; @bates2020].

## Our aim \~

In the present study, we focus on the immediate imperative of ascertaining, in the Indian context, exactly how characteristics of eBird data have been affected by the pandemic, at multiple scales. We compare eBird data quantity and quality (including metrics of birder behaviour) before, during and after the pandemic. We also compare patterns of bird species reporting, to look for artefactual effects of the pandemic and pandemic-driven changes in bird abundance and behaviour. We thus outline the consequences of the pandemic on the birding community and on some Indian birds. Further, we discuss implications and propose guidelines for making the most of the available data while accounting appropriately for pandemic-driven biases and deviations from pre-COVID normals.

# Methods

## Data preparation

We used the "relMay-2022" version of the publicly available [eBird Basic Dataset (EBD)](https://ebird.org/data/download/ebd) for India, containing all data uploaded until 31 May 2022 [downloaded on 15 June 2022; follows taxonomy in @clements2019]. We combined [sensitive species data](https://ebird.org/india/news/ebird-sensitive-species/), which is not included in the public download, after requesting separately from eBird. Before analysis, we applied a set of filters to standardise the dataset, so as to prevent any extreme and outlying cases from skewing patterns.

First, we filtered the dataset for "complete checklists", in which observers report all the birds they see or hear. Next, we filtered the data for our timeline of interest. The migratory cycle in India starts in June of one calendar year and ends in May of the next, and this time frame is thus deemed more appropriate than a calendar year. Therefore, all analyses presented in this study use "migratory year" as a unit time period and we analysed data over a period of four migratory years, from 1 June 2018 to 31 May 2022 `fig1`. We consider a relatively fine temporal scale of months in order to account for within-year variations in bird and birder behaviour. Moreover, in India severe COVID-19 restrictions and lockdowns were limited to a few months in 2020 and 2021 `ref`, and this scale allows us to consider these patterns separately from patterns in other months of the "pandemic years" (the migratory years 2019 and 2020, coded as "DUR"; 2018 and 2021 coded as "BEF" and "AFT" respectively).

`fig1: timeline of study period showing migratory years coloured by COVID category`

We then removed data from group accounts, which are eBird accounts with which multiple existing eBirders share their lists to track aggregate summaries. Such accounts are commonly used during specific events or surveys, and need to be removed from analyses of observer-related metrics. Next, we applied a nocturnal filter to remove observations made between 8pm and 4am (nocturnal birding is very different from diurnal birding), a pelagic filter to remove observations made from beyond the shoreline of the country, and finally a set of effort filters to remove observations made with extreme values of effort: checklists that are too short (less than three minutes long, or reporting three or fewer species without information on duration, or reporting three or fewer species at a rate lower than two species per hour), and travelling checklists that are too fast (following "Traveling" protocol and travelling faster than 20 kmph or covering a distance greater than 50 km). These lists with extreme effort are not considered to be "truly complete" checklists. The dataset at this stage was used in analyses of observer-level metrics (see details below), while for non-observer-level data metrics and metrics of bird reporting, a final filter was added: in instances of group birding where each participant eBirder owns a copy of the checklist, duplicate records/checklists were removed by filtering out non-unique combinations of group birding event (column "GROUP.IDENTIFIER") and bird species (column "COMMON.NAME"). The checklists that passed these criteria are hereafter referred to as "qualifying checklists".

We gridded the spatial extent of the country into 25 km × 25 km cells and used the latitude-longitude information associated with each of these qualifying checklists to place them in corresponding grid cells. In addition, we used remote sensing data to divide the country into urban and non-urban (rural) areas. For this, we downloaded the MODIS Land Cover Type Product [MCD12Q1; @friedl2019] that includes several science datasets (SDSs) mapping global land cover at a 500 m resolution. Although this comes at an annual time step, we used data from the single time point, 31 December 2021. The tiled MODIS data was downloaded using the "getModis()" function in the *luna* (`cite luna`) package and saved as individual .tif files, which were then merged into a single raster. After cropping and masking to the country's administrative boundary shapefile, the MODIS land cover categories in the raster were reclassified: category 13, "urban and built-up lands" was considered "urban", and all other categories were considered "non-urban". We didn't use the MODIS data at 500 m × 500 m resolution because the location information in eBird data, despite being precise, is not very accurate at small grain sizes (due to the very nature of eBird data where sampling often occurs over a distance). So, finally we aggregated the raster to a resolution of 2 km × 2 km which was deemed most appropriate, then classified each qualifying checklist in the dataset as urban or non-urban by extracting the land cover class from the modified MODIS raster, again using the latitude-longitude information.

## Analysis of data quantity and quality

We explored the presence of effects of the pandemic on eBird data from India by analysing changes in data quantity and quality with the pandemic. To this end, we devised a suite of metrics `table1` that help gauge various aspects of data quantity and quality. These metrics were compared at the monthly level across our years of interest, i.e., the metrics were calculated per month, across the four years. Moreover, all the metrics except for spatial spread and temporal spread `(urban bias also?)` were analysed at two spatial scales: for the whole country and for each of four states. The four states we considered in our study in order to highlight nuances were Karnataka, Kerala, Maharashtra and Assam. These states have relatively high eBirding activity and cover different regions of the country, but also differ in stage and culture of the birding community as well as in local governance, policy and general public perspective.

### Metrics of birdwatcher behaviour

1.  *Group birding* (observer-level): Were there fewer instances of group birding during the pandemic? For this, we calculated the proportion of an observer's total submitted qualifying lists that were instances of group birding, defined as birding events with three or more observers.

2.  *Site fidelity* (observer-level): Given the various restrictions on movement and travel, did birdwatchers show higher site fidelity during the pandemic? In other words, were their birding activities restricted more to certain sites than previously? Here, we considered each of `XX` 25 km × 25 km grid cells across the country as being a unique "site", and calculated the number of such unique sites visited by a birder.

3.  *Birding time* (observer-level): Did birders overall spend less time birding during the pandemic? We calculated total birding time by summing observation durations across all qualifying checklists submitted by an observer.

4.  *Hotspot birding*: eBird "hotspots" are public birding locations demarcated by eBird users to aggregate and display data from multiple birders [@ebird2022]. Given the overall decline in public/social interactions during the pandemic, did people also tend to avoid birding in eBird hotspots? We calculated, out of total submitted qualifying lists, the proportion that was from eBird hotspots.

5.  *Birding protocol*: "Traveling" and "Stationary" are the two most commonly followed protocols in eBird observations. Considering the restrictions on movement during the pandemic, we wondered whether birders also avoided making travelling lists, instead preferring stationary lists from their residences. We calculated, out of total submitted qualifying lists, the proportion that used the "Traveling" protocol.

6.  *Birding distance*: Among the observations that followed the "Traveling" protocol, we asked whether travelling distances were overall shorter during the pandemic. Here, we simply used the distance travelled, measured as part of the checklist-level effort metadata.

7.  *List duration*: Did eBird checklists become shorter in duration during the pandemic? Rather than calculating the overall time spent birding (as in 3), we considered effort at the checklist level and used checklist duration from the effort metadata.

8.  *List length*: List length is defined as the total number of species observed in a checklist. This metric is known to be a better predictor of effort than distance or duration (Viswanathan in press), and we used it to answer, from a different angle, the question of whether checklists became shorter during the pandemic.

9.  *Temporal spread*: Did the pandemic bring a change in when birders chose to observe birds? We looked at how checklists were distributed proportionally over two temporal scales: across the seven days of a week, and across the twenty-four hours of a day (although in the latter case our dataset was truncated due to our nocturnal filter).

### Urban bias

A majority of eBird users in general are urban-dwelling. With the pandemic limiting people's movements, was birding concentrated much more strongly in urban areas during the pandemic than otherwise? At the 25 km × 25 km grid cell level, we calculated the proportion of lists in each cell that were urban.

### Spatial coverage

A decrease in overall coverage of the data from the pandemic was a major concern, due to the restrictions on travel. We calculated the proportion of 25 km × 25 km grid cells across the country that were covered in each time period. The information threshold for a grid cell to be considered "covered" was set at 5 qualifying checklists (per month per year).

### Spatial spread

Did the pandemic create spatial clusters of positive or negative change in birding activity across grid cells in the country, or were changes in birding (if any) relatively uniformly spread out? For each grid cell, we calculated proportional change in birding activity (number of qualifying lists submitted) for transition periods ("BEF" to "DUR" and "DUR" to "AFT", where "DUR" was an aggregate of migratory years 2019 and 2020). Here, the COVID time periods were our temporal unit of focus, and not months. See `S1.2` for details on how this metric was calculated and interpreted.

### Statistical validation

For all metrics except spatial spread, unless otherwise mentioned, the above analyses were first done using exploratory visualisations, following which emerging patterns were validated using simple confidence calculations or bootstrap validation in some cases (see `S1.1`). Finally, after the metrics and analysis approaches were deemed meaningful, they were tested statistically using Generalised Linear Mixed Models (GLMMs). For this, we used the "glmer()" function in the *lme4* package (`cite lme4`) For the observer-level metrics (group birding, site fidelity, and birding time), observer identity was used as the random effect, whereas spatial identity defined by grid cell ID was used as the random effect for all other models `(nested within district for the urban bias model??; table1)`. All GLMMs were fit with binomial error distribution and cloglog link function, using BOBYQA optimiser.

Some metrics like observer-level site fidelity, observer-level birding time, birding distance, list duration and list length were either whole number or continuous numerical variables that did not include zero in the range of possible values. For these, since GLMMs with binomial or Poisson error distributions are not appropriate, we instead fitted LMMs (Linear Mixed Models) with the same fixed and random effects specifications and using BOBYQA optimiser, after first log-transforming (natural) the response variables to ensure normality. This was done using the "lmer()" function in *lme4*. The various models of data metrics and their specifications are listed in `table1`. There was no model run for temporal spread due to it being a visual metric and its analytical specifications being very different from those of other metrics (`S1.3`).

diagnostics

We used the "bootMer()" function in *lme4* in order to test the significance of the fitted model results, by obtaining mean and CI estimates using semi-parametric bootstrapping. The bootstrapping was done with 1000 simulations and with parallel core processing (package *parallel* `cite parallel`).

`table1` (a large sideways full-page table of metrics of data quantity and quality, and model specifications)

## Analysis of bird species reporting

To ascertain whether any of the changes in data quantity and quality during the pandemic impacted bird species reporting, or whether reporting changed at all due to any other factor, we conducted two major analyses involving two sets of commonly and easily observed bird species, one set of species common in human-dominated (urban) areas and the other uncommon in urban areas. Since not all species are widespread and equally abundant in different parts of the country, there were a few replacements in the species sets for different regions. Overall, we considered `xx` species in this study, of which `yy` were classified as "urban" and `zz` as "rural". Details of the region-wise species sets are provided in `table2`.

### Overall species reporting

In each of the four states analysed in our study, we also selected one of their large metropolitan (urban) cities. For every species in the corresponding regional species set, we visualised individual species reporting patterns at two temporal (months, migratory years) and spatial (city, state) scales. (Analysing species reporting patterns at the national level is not appropriate, considering the large variation in species ranges and abundances.) This was done by calculating the reporting frequency (proportion of qualifying checklists in which a species was reported) of each species at each scale.

We then pooled data from all urban and all rural species, and analysed whether overall species reporting patterns at the large scale (migratory years & state) were affected by the pandemic. This gave us an idea of how urban and rural species idiosyncratically differed in terms of general reporting, how species reporting varied across urban areas and how this averaged out over a large spatial scale, and how species reporting varied over the course of a year and how this variation was expressed at the large temporal scale. Kamrup Metropolitan, the metropolitan capital of the state of Assam, did not have sufficient data for visualisation of month-level patterns, so this combination was dropped.

`table2: regionwise species sets used in analyses`

### Species reporting with consistent effort

The quality of citizen science data is contingent on observer effort; it is possible for changes in observer effort to produce artefactual changes in metrics such as reporting frequency. Given the existence of biases in effort driven by birder behaviour, it then becomes difficult to make inferences from such data. Hence, in order to ensure that the patterns visible in overall bird species reporting at the large scale are not driven by changes in data quantity and quality, we conducted a similar analysis using data only from "prolific" birders having consistent effort. An eBirder was considered "prolific" if they had submitted, from a single location, at least 800 qualifying checklists over the course of the four years being analysed (sufficient effort), as well as a minimum of 15 qualifying checklists per month in at least ten months of a year in all four years of the study (consistent effort)\-\--thus translating to about 200 qualifying checklists per year. Since the observer remains constant, and the observer is sufficiently experienced (as inferred from their prolificacy), we assume that detectability of birds in the location also remains similar over the years. Therefore, this analysis allows us to make a reasonable conclusion regarding actual behavioural changes in birds.

From the set of species analysed in the previous section, we determined those to be analysed for each prolific birder by first filtering out uncommon species, retaining only those with an overall reporting frequency (over the entire study period) of at least 15%. Next, from the set of species that passed the first filter, we removed those that appeared in only one location (i.e., was observed by only one prolific birder), since a factor with only one level cannot be used as a random effect in a GLMM. Finally, if any prolific birder (their location) was left with species falling in less than two species categories (i.e., urban and rural) after the filters, they were excluded from the analysis.

### Statistical validation

Like with the metrics of data quantity and quality, the bird reporting patterns were first explored using visualisations, then emerging patterns were validated using simple bootstrapping for confidence estimates as in `S1.1`, except that the bootstrapped values were calculated separately for each spatial scale and propagation was done from the fine temporal scale of month to the scale of migratory year. Eventually, once the specifics of the analyses were finalised, the patterns were statistically tested using GLMMs. Due to strikingly obvious differences in birding conditions between the lockdown and non-lockdown periods (and due to large differences in results from both approaches), we ran three separate models: one for the months of April and May ("lockdown", `ref`), one for the other ten months ("non-lockdown"), and one for all twelve months together ("all"). This also helps determine whether the effects of the pandemic on species reporting were restricted to the strict lockdown period.

For each of these three time periods, overall bird reporting models were run for each species with grid cell ID as the random effect, while models for reporting patterns with consistent effort were run for each highly birded location with species identity as the random effect. The full model specifications are provided in `table3`. All GLMMs were fit with binomial error distribution and cloglog link function, using BOBYQA optimiser, except in a few `(how many?)` of the overall bird reporting models in which the state-species combination could not be modelled successfully due to either step-halving or convergence issues. In such cases, the canonical link function (logit) was used instead.

diagnostics same as birder

Mean and CI estimates were obtained for the fitted models in the same way as outlined in `Section 2.2.5`, but with 500 simulations instead of 1000, due to computational limitations.

`table3: a large sideways table of model specifications of bird reporting patterns`

## Software

R, RStudio, packages

The source code for the entire analysis, from data preparation to statistical validation of metrics, are available at `code repo`.

# Results

Our eBird dataset contained `How many numbers of lists after filtering?` after applying all the filters.

`table4` of metrics and their overall patterns: + or - (as in BMS2022 poster)

## Data quantity and quality

Most changes to data quantity and quality were restricted to a few months around the peak pandemic and major lockdowns, and this change was consistent across different spatial units for all metrics, with very few exceptions. Regardless of whether or not there was a change during the peak pandemic months, all metrics of birder behaviour, spatial coverage, spatial spread and urban bias remained unaffected at the large temporal scale of year `(refer to YEAR coefficients in a couple of the model summaries in the supplementary, showing that there were no long-lasting effects)`.

### Birdwatcher behaviour

During the peak pandemic months, group birding per observer decreased considerably `(fig2)`, while site fidelity per observer increased `(fig2)`. Birding in general became shorter in terms of distance covered, birding duration and list length `(fig in S2.2)`. Proportions of hotspot birding and travelling protocol lists decreased (`fig2`). These short-term changes were unsurprising, but the only noticeable long-lasting effects of the pandemic were in group birding per observer, site fidelity per observer, hotspot birding and birding protocol, which were all restricted to the lockdown months in 2020 but in 2021 decreased across a large part of the year `(fig2)`. Moreover, birding distance `(fig in S2.2)` at the national level declined after MY 2018, including in MY 2021 after the pandemic.

Thus, the effects of the pandemic on birder behaviour were not consistent throughout the pandemic. The changes were more drastic in 2020 than in 2021, even during the peak pandemic months of both years. In the case of observer-level group birding and site fidelity, and hotspot birding and birding protocol, 2021 had a lower magnitude of change compared to 2020 but the change spanned more months of the year. However, these long-term declines were only present at the national level; at the level of individual states, these patterns were highly variable `(fig S2.3)`.

The effect on the birding distance metric, interestingly, was higher in 2020 during the peak period but lower in 2020 during several other months of the year. Moreover, there was no observable decline at all in overall birding effort in terms of time spent birding by an average observer `(model in S3; fig4)`.

`fig2: group birding per observer, site fidelity per observer, hotspot birding, birding protocol (national)`

### Urban bias

As expected, urban birding proportion increased `(fig3)` during the peak pandemic months, and reverted to pre-pandemic levels as the period of peak lockdowns passed.

`fig3: urban birding proportion`

### Spatial coverage

There is a slight suggestion of a small decrease in spatial coverage during April 2020, but it has only increased in every successive month since. However, this has not resulted in any observable decline in overall area covered by birders (i.e., at the large temporal scale) `(model in S3)`. In fact, there are even suggestions of a slight increase in these metrics over the years `(fig4)`. Additionally, this slight decrease at the national level was mirrored only by some states like Kerala, while coverage either stayed the same (e.g., Karnataka `fig S2.5`) or even kept increasing (e.g., Maharashtra `figS2.5`) in others.

### Spatial spread

Importantly, there was no worrisome spatial clustering or concentration of the fine-scale changes to overall birding effort `(fig5)`.

`fig4: graphs of birding time, spatial coverage`

`fig5: graphs of spatial spread; one each of no. lists, grid coverage with threshold`

## Bird species reporting

Overall bird species reporting patterns for the states of Karnataka, Kerala, Maharashtra and Assam were explored for 23 species (11 urban, 12 rural), 21 species (11, 10), 22 species (11, 11) and 19 species (10, 9) respectively. The analysis of reporting patterns with consistent effort considered 20 species (11, 9) common to all `how many` qualifying locations across the country. In general, urban species are reported more frequently than non-urban species. Across all these analyses, there exists high variability at the fine scale that often evens out at larger scales.

### Overall species reporting

During the peak periods of the pandemic, urban species reporting increased in all states `(fig6)`. However, the states varied in how reporting frequency of non-urban species changed. In Karnataka, while urban species reporting increased, non-urban species reporting stayed the same. In Kerala and Assam, the increase in urban species reporting was accompanied by an increase in non-urban species reporting, though the increase in non-urban species was smaller than that of urban species in Assam. Maharashtra was the only state where non-urban species reporting decreased during the peak pandemic months.

The patterns in Kerala are consistent at both temporal scales, whereas at the annual level Maharashtra mirrors the patterns in Kerala. At the annual scale, Assam retains the higher urban reporting during the pandemic year while non-urban reporting did not change. The small-scale increase in urban species reporting in Karnataka is not reflected at the annual scale, resulting in no notable effect on either species category. Importantly, at this large scale it becomes evident that the pandemic did not result in a decrease in non-urban species reporting.

Different species within the same category sometimes showed contradictory patterns `(refer annual graph of some state)`. Often, species exhibited patterns contradictory to the expectations of pandemic effects: urban species reporting decreased (e.g., `KA annual graph`) or non-urban species reporting decreased (e.g., `KL annual graph`). Patterns also generally soften out (effect sizes decrease) across space, time or species. Thus, in most cases there is no clear and noticeable directional effect of the pandemic of bird species reporting.

### Species reporting with consistent effort

These patterns show a different picture at the small scale in that neither urban nor non-urban species reporting increased or decreased notably during the peak periods, as the highly variable local patterns average out across space `(fig7)`. This is true at the large scale of years as well, suggesting at the very least that there was no inherent change in birds that made them more or less active/bold, detectable or abundant during the pandemic.

`fig6: 2 months of all states overall models`

`fig7: all three panels of prolific models`

# Discussion

There is a general paucity of studies looking at the effects of the pandemic on citizen science data characteristics, as most focus on changes in the organisms instead, even if using data from citizen science programmes [e.g., @warrington2022]. We expected changes to the quantity and quality of eBird data during the pandemic due to behavioural changes in the birding community caused directly by the various restrictions and indirectly by lifestyle changes. Interestingly, our results suggest that official restrictions introduced during the peak periods of the pandemic, including the various lockdown periods, were more instrumental in changing birder behaviour, while changes in lifestyle were not drastic or long-lasting enough to affect birder behaviour in the long run.

## Did data quantity increase or decrease?

Elsewhere, despite the various restrictions on movement and social interaction during the strict lockdowns, participation increased in CS programmes such as eBird [@hochachka2021; though @crimmins2021 found a decline] and iNaturalist [@crimmins2021], as did the amount of data generated [@hochachka2021; @crimmins2021]. Our results are in agreement (fig`S2.1` number of lists, fig`S2.1` number of active/new eBirders) with this general increase in data quantity.

## How did birders behave?

We found that while overall birding effort did not decrease during the pandemic (`observer-level birding time`), birders shifted their behaviours in certain expected ways during the peak lockdown periods in India. The most obvious and direct change was due to the various restrictions on movement, travel and social interaction: birders avoided interacting with other birders (`group birding per observer` graph), and became more sedentary by limiting travel (`observer-level site fidelity graph`) and staying put (`graphs of birding protocol, hotspots`). Birding effort at the level of individual checklists decreased during lockdown, with lists becoming shorter overall (`S graphs of list length, distance, duration`), but this must not be confused with overall birding effort which did not decrease. These trends also varied depending on the specific area (`state-level graph of something`) and scale under consideration. Importantly, these fine-scale changes in checklist-level effort were not concentrated in any notable way in space, i.e., major changes were not located all in certain parts of the country (`fig5`).

## Is the quality of pandemic data a concern?

These changes in birder behaviour imply multiple things for eBird data quality. The lower mobility of birders also meant a slight decline in overall spatial coverage of the data just in April 2020 (`fig4`), although this quickly reverted to normal levels and did not translate to larger or longer-term changes. In fact, overall spatial coverage has only been increasing, owing to the birding community in India bring in the exponential phase of growth.

Since a large majority of the eBirding community is urban, birders becoming more sedentary also meant a clear bias towards urban areas in the data generated during the lockdown periods. This urban bias was much more prominent during the first lockdown than the second, despite the latter year having been more devastating in terms of COVID-19 cases, and thus did not result in larger or longer-term changes to data quality relative to pre-COVID standards. Moreover, the individual fine-scale, often contradictory, variations in metrics of data quality were spread throughout the country and not concentrated in one or a few specific regions.

Nevertheless, if these fine-scale changes to the nature of eBird data also resulted in artefactual changes in bird species reporting patterns, this would have consequences for how useful data from these years is. For instance, increased dominance of urban observations could artificially inflate the reporting frequencies of species found more commonly in urban areas than in non-urban areas. Indeed, we found that at the large scale, birders in some states reported urban species slightly more frequently during the pandemic than before, while those in other states did not. However, for the former states, this change remained even after the pandemic, suggesting that it might not have been due to the pandemic. Importantly, at this scale birders did not report non-urban species less frequently.

Thus, there was some evidence of directional change in urban species reporting although this was not consistent across space. We found no clear evidence of any consistent directional change in reporting frequencies of commonly observed non-urban species at the large scale. Therefore, the quality of eBird data from India during the pandemic does not seem different enough to be a concern for analytical applications of this data.

## Did bird behaviour or abundance change?

Not only do anthropogenic factors affect birds via habitat availability, suitability, survival and fitness, etc., but many of their behavioural traits are also directly affected by human activity (e.g., song amplitude and frequency, time of vocal activity, etc.). Indeed, during the period of most stringent restrictions in USA, although a few species showed a decline, most increased in abundance in areas that saw a decrease in human activity [@schrimpf2021]. In contrast, species tightly linked to human presence and activity like the Feral Pigeon showed lower abundances [@soh2021]. Moreover, these behavioural traits can change rapidly in response to environmental changes [@derryberry2020; @sanderfoot2022; @hentati-sundberg2021; @gordo2021; but see @seress2021].

To ascertain whether or not this was the case in the Indian context, we checked once again for differences in bird species reporting, but this time after accounting for the confounding variability in effort. If some changes in species reporting patterns emerged from this data with consistent effort, it would suggest some response of birds to the reduced human activity, such as changes in bird abundance or behaviour.

However, we found no evidence for birds becoming more or less bold, detectable or abundant during the pandemic. This might be because a few months of reduced human activity is insufficient to cause changes in large-scale patterns of bird behaviour or occurrence [see @seress2021]. Despite the presence of both positive and negative trends at very local scales, our results show the high degree of variability in these patterns across species, space and time. These are often contradictory and hence balance each other out, which could explain the lack of a clear directional signal of change. Nevertheless, we conclude that there is no consistent evidence of birds being affected by the pandemic, positively or negatively, artefactually or otherwise.

## What happened during the peak pandemic months?

Most changes to data quality were concentrated in the months of April and May of 2020. This was the first pandemic year and these months involved some of the most stringent restrictions and government regulations (e.g., nationwide lockdown) in order to curb the spread of the pandemic [@bbcnews2020; @gettleman2020; @theeconomictimes2020]. This, together with the novelty and shock of the experience, could explain why the changes in birder behaviour were more drastic in 2020 than in 2021 although the latter was even more devastating in terms of casualties [@worldometer2022].

Soon after the restrictions were lifted, birders returned to their usual behaviours, except with certain obvious choices like avoiding birding in groups. As a result, the changes that the pandemic brought to human life did not lead to a prominent change at the large scale in how different bird species were reported.

## How useful is eBird data from the pandemic?

Since there is no evidence of bird species reporting having been affected by the nature of the data collection, eBird data from the pandemic years is still immensely valuable. In fact, our results highlight certain key points about using this data and making inferences from it.

### Importance of scale

@hochachka2021 emphasised spatial scale considerations by showing the presence of high degrees of regional variability in the effects of the pandemic. However, they only considered a single month across years, and so failed to capture variability across temporal scales. Our findings highlight the importance of both spatial and temporal scales in considering the effects of a major event like the COVID-19 pandemic.

At the small scale of months and states (or even smaller like districts), there were clear and expected changes in birder behaviour and, consequently, to data quality. There was also high variability across states. Most of these changes reverted to "normal" levels after the lockdown months, or averaged out across different states, hence resulting in very few notable nationwide changes at the larger temporal scale of years. Most analyses of long-term abundance trends or distributions or migratory patterns using eBird data are carried out at such large scales.

### Guidelines for using pandemic eBird data from India

From the results of our study, we can conclude that eBird data from India from the pandemic years is still a valuable asset. When formulating a question to be answered using this data, the researcher must first consider the scale (spatial and temporal) of the question. Questions of larger scale can be tackled directly, whereas small-scale questions will benefit from a deep-dive into artefactual patterns in the raw data that can potentially create misleading patterns. In the latter cases, the researcher is recommended to conduct similar analyses to the ones in this study in order to first assess the suitability of the data before attempting to answer the question. Nevertheless, there is still tremendous potential for CS data like eBird in exploring large-scale patterns.

# Conclusion

# References
