---
title: "Literature Review"
author: "Karthik Thrikkadeeri"
date: "08/12/2021"
editor_options: 
  chunk_output_type: console
bibliography: covid-ebirding.bib
link-citations: yes
output: 
  html_document:
    toc: false
    number_sections: false  
    theme: united  
    highlight: tango  # specifies the syntax highlighting style
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Literature review

The lockdowns offer an invaluable opportunity to assess the impacts of human activity, to discern this from the effects of other anthropogenic factors, and to identify organisms that are most affected and vulnerable by this @rutz2020.

## Birder behaviour

Start by elaborating on how sampling process/effort can vary temporally. Detection probabilites may change.

Two essentially contradictory possibilities: birding decreased due to restrictions on movement (and perhaps other life priorities), or birding increased due to greater desire for natural connections as well as active encouragement through outreach programmes.

Quantity as well as quality of data. Spatial (clustered data) and temporal bias. Rare habitats (wetlands?) undersampled. 

@hochachka2021 found an alteration in birder behaviour in April 2020, but this was not as substantial as would be expected given the magnitude of change to daily life. Main biases seen were in **representation of habitats** and **observer effort**. Notably, other moments of distribution than mean, like variance, were as important. In their comparison of four political units, they found different patterns in all of them, pointing to the differences in political and policy responses across the world and suggesting that these regional differences be taken into account when using eBird data. However, their conclusions and inferences only hold for the month of April 2020, with the strict lockdowns in place. Most studies looking at temporal trends would compare years, without going to the finer scale of individual months. Hence, it is important to ascertain how exactly the eBird dataset would have been affected by the overall "COVID period" rather than just the full lockdowns.

@randler2020 found that the pandemic-induced lockdown has caused significant changes in spatial, temporal, social, demographic and country-related aspects of birding. 

@basile2021 found an increase in urban citizen science (iNat) observations during the pandemic year, compared to previous years. Non-urban observations decreased in some countries but remained similar in others. They also found a general decrease in "new records". 

## Bird behaviour

@schrimpf2021 found that birds mostly increased in abundance in areas that saw decrease in human activity, during the period of most stringent restrictions, although some species showed the opposite pattern. They used various metrics of human activity. 

@derryberry2020 showed that behavioural traits can change rapidly in response to new changes in environmental conditions. They found that traffic noise levels in urban areas during the lockdown decreased significantly, going down to mid-1950s levels, and that birds produced higher performance songs at lower amplitudes, maximising communication distance and salience. (Acoustic differences)

@gordo2021 found that in urban areas the lockdown did not cause higher occurrence rates than before. Some species showed marginal increases, probably due to more intensive urban sampling during the lockdown. Detection probability of birds in urban areas throughout the day increased during the lockdown, especially during the early hours. (Ornitho)

@mikula2021 showed that the wearing of face masks did not result in changes in antipredatory behaviour of birds as measured by flight initiation distance. 



