# Supplementary Material

## Figures

### Overall bird reporting

```{r overall-non1, fig.cap="Calculated monthly reporting frequencies for urban (A) and rural (B) species in Bengaluru city. Points represent means while error bars show 95% confidence intervals. Values for the four migratory years are shown in different colours, and the peak pandemic months are shown in red text.", out.width="100%", fig.width=8, fig.height=13, dpi=300, dev="jpeg"}

load("00_outputs/b01_overall_s1a_m.RData")
d1 <- data_a %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)
d2 <- data_a %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)

p1 <- ggplot(d1, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency")

(p1 / guide_area() / p2) +
  plot_layout(guides = "collect", heights = c(6, 0.5, 6)) +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 5),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(MONTH.LAB, COL1))$COL1))

```

```{r overall-non2, fig.cap="Calculated monthly reporting frequencies for urban (A) and rural (B) species in Karnataka state. Points represent means while error bars show 95% confidence intervals. Values for the four migratory years are shown in different colours, and the peak pandemic months are shown in red text.", out.width="100%", fig.width=8, fig.height=13, dpi=300, dev="jpeg"}

d1 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)
d2 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)

p1 <- ggplot(d1, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency")

(p1 / guide_area() / p2) +
  plot_layout(guides = "collect", heights = c(6, 0.5, 6)) +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 5),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(MONTH.LAB, COL1))$COL1))

```

```{r overall-non3, fig.cap="Calculated annual reporting frequencies for urban (A) and rural (B) species in Bengaluru city. Points represent means while error bars show 95% confidence intervals, and the peak pandemic years are shown in red text.", out.width="100%", fig.width=8, fig.height=11, dpi=300, dev="jpeg"}

load("00_outputs/b01_overall_s1b_y.RData")
d1 <- data_a %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)
d2 <- data_a %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)

p1 <- ggplot(d1, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency")

(p1 / p2) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 7),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(M.YEAR, COL3))$COL3))

```

```{r overall-non4, fig.cap="Calculated annual reporting frequencies for urban (A) and rural (B) species in Karnataka state. Points represent means while error bars show 95% confidence intervals, and the peak pandemic years are shown in red text.", out.width="100%", fig.width=8, fig.height=11, dpi=300, dev="jpeg"}

d1 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)
d2 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)

p1 <- ggplot(d1, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency")

(p1 / p2) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 7),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(M.YEAR, COL3))$COL3))

```

```{r overall-non5, fig.cap="Calculated monthly reporting frequencies for urban (A) and rural (B) species in Kochi city. Points represent means while error bars show 95% confidence intervals. Values for the four migratory years are shown in different colours, and the peak pandemic months are shown in red text.", out.width="100%", fig.width=8, fig.height=13, dpi=300, dev="jpeg"}

load("00_outputs/b01_overall_s2a_m.RData")
d1 <- data_a %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)
d2 <- data_a %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)

p1 <- ggplot(d1, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency")

(p1 / guide_area() / p2) +
  plot_layout(guides = "collect", heights = c(6, 0.5, 6)) +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 5),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(MONTH.LAB, COL1))$COL1))

```

```{r overall-non6, fig.cap="Calculated monthly reporting frequencies for urban (A) and rural (B) species in Kerala state. Points represent means while error bars show 95% confidence intervals. Values for the four migratory years are shown in different colours, and the peak pandemic months are shown in red text.", out.width="100%", fig.width=8, fig.height=13, dpi=300, dev="jpeg"}

d1 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)
d2 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)

p1 <- ggplot(d1, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency")

(p1 / guide_area() / p2) +
  plot_layout(guides = "collect", heights = c(6, 0.5, 6)) +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 5),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(MONTH.LAB, COL1))$COL1))

```

```{r overall-non7, fig.cap="Calculated annual reporting frequencies for urban (A) and rural (B) species in Kochi city. Points represent means while error bars show 95% confidence intervals, and the peak pandemic years are shown in red text.", out.width="100%", fig.width=8, fig.height=11, dpi=300, dev="jpeg"}

load("00_outputs/b01_overall_s2b_y.RData")
d1 <- data_a %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)
d2 <- data_a %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)

p1 <- ggplot(d1, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency")

(p1 / p2) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 7),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(M.YEAR, COL3))$COL3))

```

```{r overall-non8, fig.cap="Calculated annual reporting frequencies for urban (A) and rural (B) species in Kerala state. Points represent means while error bars show 95% confidence intervals, and the peak pandemic years are shown in red text.", out.width="100%", fig.width=8, fig.height=11, dpi=300, dev="jpeg"}

d1 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)
d2 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)

p1 <- ggplot(d1, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency")

(p1 / p2) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 7),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(M.YEAR, COL3))$COL3))

```

```{r overall-non9, fig.cap="Calculated monthly reporting frequencies for urban (A) and rural (B) species in Pune city. Points represent means while error bars show 95% confidence intervals. Values for the four migratory years are shown in different colours, and the peak pandemic months are shown in red text.", out.width="100%", fig.width=8, fig.height=13, dpi=300, dev="jpeg"}

load("00_outputs/b01_overall_s3a_m.RData")
d1 <- data_a %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)
d2 <- data_a %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)

p1 <- ggplot(d1, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency")

(p1 / guide_area() / p2) +
  plot_layout(guides = "collect", heights = c(6, 0.5, 6)) +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 5),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(MONTH.LAB, COL1))$COL1))

```

```{r overall-non10, fig.cap="Calculated monthly reporting frequencies for urban (A) and rural (B) species in Maharashtra state. Points represent means while error bars show 95% confidence intervals. Values for the four migratory years are shown in different colours, and the peak pandemic months are shown in red text.", out.width="100%", fig.width=8, fig.height=13, dpi=300, dev="jpeg"}

d1 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)
d2 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)

p1 <- ggplot(d1, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency")

(p1 / guide_area() / p2) +
  plot_layout(guides = "collect", heights = c(6, 0.5, 6)) +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 5),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(MONTH.LAB, COL1))$COL1))

```

```{r overall-non11, fig.cap="Calculated annual reporting frequencies for urban (A) and rural (B) species in Pune city. Points represent means while error bars show 95% confidence intervals, and the peak pandemic years are shown in red text.", out.width="100%", fig.width=8, fig.height=11, dpi=300, dev="jpeg"}

load("00_outputs/b01_overall_s3b_y.RData")
d1 <- data_a %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)
d2 <- data_a %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)

p1 <- ggplot(d1, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency")

(p1 / p2) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 7),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(M.YEAR, COL3))$COL3))

```

```{r overall-non12, fig.cap="Calculated annual reporting frequencies for urban (A) and rural (B) species in Maharashtra state. Points represent means while error bars show 95% confidence intervals, and the peak pandemic years are shown in red text.", out.width="100%", fig.width=8, fig.height=11, dpi=300, dev="jpeg"}

d1 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)
d2 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)

p1 <- ggplot(d1, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency")

(p1 / p2) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 7),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(M.YEAR, COL3))$COL3))

```

```{r overall-non13, fig.cap="Calculated monthly reporting frequencies for urban (A) and rural (B) species in Assam state. Points represent means while error bars show 95% confidence intervals. Values for the four migratory years are shown in different colours, and the peak pandemic months are shown in red text.", out.width="100%", fig.width=8, fig.height=13, dpi=300, dev="jpeg"}

load("00_outputs/b01_overall_s4a_m.RData")
d1 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)
d2 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR, MONTH.LAB)

p1 <- ggplot(d1, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(MONTH.LAB, REP.FREQ, colour = M.YEAR)) +
  geom_point(size = 1.5, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 0.75, width = 0.75, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 2, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Month", y = "Reporting frequency")

(p1 / guide_area() / p2) +
  plot_layout(guides = "collect", heights = c(6, 0.5, 6)) +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 5),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(MONTH.LAB, COL1))$COL1))

```

```{r overall-non14, fig.cap="Calculated annual reporting frequencies for urban (A) and rural (B) species in Assam state. Points represent means while error bars show 95% confidence intervals, and the peak pandemic years are shown in red text.", out.width="100%", fig.width=8, fig.height=11, dpi=300, dev="jpeg"}

load("00_outputs/b01_overall_s4b_y.RData")
d1 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "U") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)
d2 <- data_b %>% ungroup() %>% filter(SP.CATEGORY == "R") %>% 
  left_join(month_lab) %>% arrange(M.YEAR)

p1 <- ggplot(d1, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency") 

p2 <- ggplot(d2, aes(M.YEAR, REP.FREQ)) +
  geom_point(size = 2, position = position_dodge(0.8)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U), 
                size = 1, width = 0.5, position = position_dodge(0.8)) +
  scale_colour_manual(values = covid_palette, name = "Migratory year") +
  facet_wrap(~ COMMON.NAME, dir = "h", ncol = 4, 
             strip.position = "left", scales = "free_y") +
  labs(x = "Migratory year", y = "Reporting frequency")

(p1 / p2) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") &
  theme_classic(base_size = 10) &
  theme(strip.text = element_text(size = 7),
        legend.position = "bottom",
        axis.text.x = element_text(colour = (d1 %>% distinct(M.YEAR, COL3))$COL3))

```

```{r overall-10m, fig.cap="Modelled species reporting frequencies for all ten months excluding April and May, for the states of Karnataka (A), Kerala (B), Maharashtra (C) and Assam (D). Points represent means while error bars show 95% confidence intervals. Values for urban and rural species are shown in maroon and purple respectively, and the pandemic years are shown in red text.", out.width="100%", fig.width=10, fig.height=6, dpi=300, dev="jpeg"}

load("00_outputs/b01_overall_s1c_model.RData")
d1 <- birds_pred %>% filter(MONTHS.TYPE == "NL")
load("00_outputs/b01_overall_s2c_model.RData")
d2 <- birds_pred %>% filter(MONTHS.TYPE == "NL")
load("00_outputs/b01_overall_s3c_model.RData")
d3 <- birds_pred %>% filter(MONTHS.TYPE == "NL")
load("00_outputs/b01_overall_s4c_model.RData")
d4 <- birds_pred %>% filter(MONTHS.TYPE == "NL") 

p1 <- ggplot(d1, aes(M.YEAR, PRED, col = SP.CATEGORY)) +
  scale_color_manual(values = c("#8F85C1", "#A3383C"),
                     name = "Species category",
                     labels = c("Rural", "Urban")) +
  labs(x = "", y = "Reporting frequency") +
  geom_point(size = 2, position = position_dodge(0.5)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U),
                size = 1, width = 0.5, position = position_dodge(0.5)) 


p2 <- ggplot(d2, aes(M.YEAR, PRED, col = SP.CATEGORY)) +
  scale_color_manual(values = c("#8F85C1", "#A3383C"),
                     name = "Species category",
                     labels = c("Rural", "Urban")) +
  labs(x = "Migratory year", y = "") +
  geom_point(size = 2, position = position_dodge(0.5)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U),
                size = 1, width = 0.5, position = position_dodge(0.5)) 

p3 <- ggplot(d3, aes(M.YEAR, PRED, col = SP.CATEGORY)) +
  scale_color_manual(values = c("#8F85C1", "#A3383C"),
                     name = "Species category",
                     labels = c("Rural", "Urban")) +
  labs(x = "", y = "") +
  geom_point(size = 2, position = position_dodge(0.5)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U),
                size = 1, width = 0.5, position = position_dodge(0.5)) 

p4 <- ggplot(d4, aes(M.YEAR, PRED, col = SP.CATEGORY)) +
  scale_color_manual(values = c("#8F85C1", "#A3383C"),
                     name = "Species category",
                     labels = c("Rural", "Urban")) +
  labs(x = "Migratory year", y = "") +
  geom_point(size = 2, position = position_dodge(0.5)) +
  geom_errorbar(aes(ymin = CI.L, ymax = CI.U),
                size = 1, width = 0.5, position = position_dodge(0.5)) 


(p1 | p2 | p3 | p4) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") &
  theme(legend.position = "bottom",
        plot.tag.position = c(0, 1),
        axis.text.x = element_text(colour = (month_lab %>% distinct(M.YEAR, COL3))$COL3,
                                   angle = 45, vjust = 0.5))

```

## Tables

```{r reg-spec, tab.cap='Region-wise species sets for which overall reporting patterns were analysed. "+" indicates species that were included in the analysis for the different states.'}

# regionwise species sets used in analyses

species_list %>% 
  mutate(STATE = factor(STATE, levels = c("Karnataka", "Kerala", "Maharashtra", "Assam")),
         SP.CATEGORY = factor(SP.CATEGORY, levels = c("U", "R"))) %>% 
  distinct(SP.CATEGORY, STATE, COMMON.NAME) %>% 
  arrange(SP.CATEGORY, STATE) %>% 
  mutate(PRESENT = "+") %>% 
  pivot_wider(names_from = "STATE", values_from = "PRESENT") %>% 
  mutate(SP.CATEGORY = ifelse(SP.CATEGORY == "U", "Urban", "Rural")) %>% 
  rename(Species = COMMON.NAME, `Species category` = SP.CATEGORY) %>% 
  # flextable
  flextable() %>% 
  set_table_properties(layout = "autofit") %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>% 
  align(align = "center", part = "all") %>% 
  align(align = "left", j = "Species", part = "all")

```

<br>
