# Abstract {.unnumbered}

Conventional systematic projects to monitor bird populations, like breeding bird surveys, require large and coordinated volunteer networks that are lacking in many parts of the world. Citizen science (CS) data offers an alternative to systematic initiatives in these regions, but the semi-structured nature of such data also presents several challenges. The utility of semi-structured CS data to monitor bird species abundance is contingent on how, where, and how comparably birdwatchers watch birds, year-on-year. Trends inferred directly from the data can be confounded during years when birdwatchers may behave differently, such as during the COVID-19 pandemic. We wanted to ascertain how the data uploaded to one such CS platform in India, eBird, was impacted by this deadliest global pandemic of the 21st century. To understand whether eBird data from the pandemic years in India is useful and comparable to data from adjacent years, we explored several metrics of data quantity and quality (such as birdwatcher behaviour) at multiple spatial and temporal scales. We found no negative impact of the pandemic on data quantity. Data quality (i.e., characteristics) changed largely only during the peak pandemic months characterised by high fatality rates and strict lockdowns, possibly due to decreased human mobility and social interaction. It remained similar to the adjacent years during the rest of this restrictive period, therefore reducing the impact of the aberrant peak months on any annual inference. Moreover, impacts on data quality varied widely across states in India, resulting in no strong consistent trend at the national level---unlike results from elsewhere in the world, highlighting India's unique position. Our findings show that birdwatchers in India as data collectors were resilient to disturbance, and that the effects of the pandemic on birdwatching effort and birdwatcher behaviour are highly scale- and context-dependent. In summary, eBird data in India from the pandemic years remains useful and interpretable for most large-scale applications, such as abundance trend estimation, but will benefit from preliminary data quality checks when utilised at a fine scale.

# Keywords {.unnumbered}

Birdwatcher behaviour, COVID-19 pandemic, data quality, eBird, effort

\newpage

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}

require(tidyverse)
require(patchwork)
require(glue)
require(lubridate)
require(sf)
require(magick)

theme_set(theme_classic(base_size = 16))

covid_palette <- c("#1B9E77", "#EF4050", "#E89005", "#9678B6")
# covid_palette2 <- c("#1B9E77", "#D95F02", "#7570B3", "#555555")
covid_palette3 <- c("#1B9E77", "#E89005", "#9678B6")


# month labels
month_lab <- data.frame(M.YEAR = 2018:2021) %>% 
  group_by(M.YEAR) %>% 
  summarise(MONTH = 1:12 %>% month()) %>% 
  mutate(MONTH.LAB = month(MONTH, label = T)) %>% 
  mutate(MONTH = factor(MONTH, levels = month(c(6:12, 1:5))),
         M.YEAR = factor(M.YEAR),
         MONTH.LAB = factor(MONTH.LAB, levels = month(c(6:12, 1:5), label = T))) %>% 
  mutate(COL1 = ifelse(MONTH.LAB %in% c("Apr", "May"), "red", "black"), # for normal plots
         COL2 = ifelse((M.YEAR %in% 2019:2020) & 
                         (MONTH.LAB %in% c("Apr", "May")), "red", "black"), # for timeline 
         COL3 = ifelse(M.YEAR %in% 2019:2020, "red", "black")) %>% # for bird model plots
  arrange(M.YEAR, MONTH.LAB)

# loading data required for various summaries, tables and figures
load("../../00_outputs/data_for_ms.RData")


knitr::opts_chunk$set(
  fig.retina=3,
  echo = FALSE,
  cache = TRUE, 
  include = TRUE,
  message = FALSE, 
  warning = FALSE
)

```

# Introduction

## Birds and citizen science

Citizen science (CS) today is a research technique that engages volunteers from the general public---most of whom are not trained as scientists---in collecting and/or analysing and interpreting data as a part of scientific enquiry [@silvertown2009]. CS programmes are particularly effective when they revolve around popular hobbies or activities that people enjoy, such as birdwatching. Birdwatching (hereafter birding) is a nature-based activity that is enjoyed by a large number of people around the world, making CS projects involving birds especially appealing to the public. Birders, as a matter of practice, make "checklists" of the bird species they observe during birding sessions. By volunteering this data, numerous birders---from trained researchers to experienced birders to laypersons---are able to contribute to the scientific study of birds.

Conventional "systematic" CS bird monitoring programmes [see @miller-rushing2012] that engage birders are resource- and volunteer-intensive [e.g., @greenwood1995; @barrett2003; @newson2005; @norman2012; @sauer2013a; @birdlifeaustralia2015; @harris2021; @praveen2022; @swissornithologicalinstitute2023]. In parts of the world like India where this is not feasible at large scales, CS projects having "semi-structured" protocols [@pocock2017; @dicecco2021] work better. For instance, eBird [@sullivan2014] is widely used by birders in India and enables large-scale robust scientific analysis and output [e.g., @soib2023]. eBird data has proved very useful in better understanding bird ecology, species ranges [e.g., @freeman2022; @sreekumar2021; @thrikkadeerietalWHBW], migration [e.g., @menon2023; @aoki2021; @youngflesh2021], behaviour [e.g., @winger2019; @alaniz2020], morphology [e.g., @vrettos2021; @menon2022] and conservation action [@sullivan2017; @soib2023; @ruiz-gutierrez2021].

However, a drawback is that eBird checklists vary in "effort", quality, and quantity (no single fixed protocol), violating the homogeneity of data in space and time, and therefore creating apparent biases [@johnston2021]. Largely associated with birder behaviour, such biases make the data difficult to use to inform yearly abundance trends. Although some recent analyses show that the biases can be reduced statistically to mimic inference from more systematic data (@viswanathanKBA; @viswanathanetalSoIB; @johnston2021), biases in semi-structured data become especially pronounced when there are large-scale changes in human (birder) behaviour, such as presumably during the COVID-19 pandemic. Given the widespread utility of semi-structured CS data today for conservation, an urgent question is whether the pandemic has rendered eBird data from the pandemic years unusable in combination with the rest of the dataset for estimating yearly abundance trends.

## Birding in the time of COVID-19

COVID-19 is a deadly infectious disease that resulted in the deadliest pandemic of the 21st century, with a death toll of more than 6.9 million (around 0.1% of the global population$;$ @wikipedia2023; @worldometer2023). Governments across the world had therefore taken various precautionary and preventive measures, and had implemented restrictions such as nation- or state-wide lockdowns and curfews, quarantines and self-isolation, and shutting down of non-essential public services and activities [see @hale2020]. Given that the eBird enterprise hinges entirely on public participation, this widespread public upheaval might have changed the very nature of eBird data during this period.

### How much birding?

The COVID-19 pandemic has generally posed a big challenge for CS programmes [e.g., @kishimoto2021; @hochachka2021]. Social and travel restrictions, in combination with physical and mental distress [@li2020; @vanbavel2020], may have led to a decline in the amount of hobbyist birding, and therefore in the quantity of data generated. Some CS projects did indeed show evidence of reduced participation and data generation [e.g., @kishimoto2021], but others in fact witnessed an increase in data generated [e.g., @basile2021]. Outdoor recreational activities such as birding are known to restore attention and play a vital role in improving physical and mental health [@weng2014]. The pandemic brought an increased desire in people to connect with the natural world [@marsh2021], as well as active promotion and encouragement of nature-related activities such as birding [e.g., @birdcountindia2020]. Thus, many turned to birding as their activity of choice [@randler2020].

### What kinds of birding?

Regardless of how much more or less data was generated during the pandemic, the characteristics of this data could also have changed. For example, @randler2020 found differences in aspects of birder behaviour, such as who was birding and with whom, as well as where and when birding (and thus data generation) was happening. Restricted mobility has led to data being less spread out in space, with observations being concentrated in urbanised locations [@vardi2021] and covering a lower overall diversity of habitats [@hochachka2021], thus reducing its informational value [@zhang2020]. On the other hand, @kishimoto2021 found that the restrictions resulted in lower clustering of data, potentially by forcing birders to upload observations from their erstwhile under-surveyed neighbourhoods and not from birding hotspots (either urban or rural).

### Scale and generalisability

@hochachka2021 studied changes in birder behaviour during a month-long lockdown across three countries: USA (states of California and New York), Spain and Portugal. The changes were not as substantial as expected from the magnitude of change to daily life. Notably, such studies of the pandemic impacts have not explored broader temporal scales---time scales relevant for large-scale analyses of abundance trends, such as for @soib2023. Moreover, @hochachka2021 found differential responses to the pandemic in the respective birding communities, and suggested that such differences are likely to exist amongst geographical units across the world, thus cautioning against a global generalisation of how the pandemic influenced birding and birder behaviour. Indeed, birdwatchers in India and elsewhere in the Global South may be expected to behave differently from those in North America and Europe (and therefore respond differently to events such as the COVID-19 pandemic) due to different socioeconomic realities, aspirations, and politics.

### Usefulness of semi-structured data

India's rapid recent progress in volunteer-driven bird monitoring is both unique and pioneering, showing the way forward to many countries in the Global South where large-scale resource-intensive systematic surveys may not be possible in the near future. Semi-structured data generated from birders' "casual" observations can be immensely valuable for assessing the health of a region's birds, as the State of India's Birds reports (-@soib2020 and -@soib2023) have demonstrated. Because such assessments are intended to inform conservation policy, there is an urgent need to ensure robustness of birding and of the data to disruptive events like the COVID-19 pandemic or even potential future climate crises.

## Our aim

In this study, we sought a comprehensive understanding of how birders in India may have changed their behaviour during the pandemic, and what this may indicate about the utility of the generated data. We specifically focused on the use of the platform eBird in India, and asked whether or not eBird data quantity and quality (characteristics) were similar before, during and after the pandemic. When not similar, we then tried to ascertain the extent of these changes, by assessing transience (peak pandemic months vs years) and spatial variation (states vs country). Finally, we used this understanding to synthesise the implications of the pandemic on the utility of eBird data for long-term bird monitoring---specifically for abundance trend estimation (in India and elsewhere in the Global South)---and also outlined guidelines for using this data for such applications.

# References

::: {#refs}
:::

\newpage

Supplementary Online Material (SOM) is available.
