---
title: "Birdwatchers' resilience to perturbation in India buffers citizen science from pandemic-induced biases"
author: 
  - Karthik Thrikkadeeri:
      email: karthik.t@ncf-india.org
      institute: ncf
      correspondence: true
  - name: Ashwin Viswanathan
    institute: ncf
institute:
  - ncf: 'Nature Conservation Foundation, 1311, "Amritha", 12th Main, Vijayanagar 1st Stage, Mysuru 570017, Karnataka, India'
output: 
  bookdown::word_document2:
    number_sections: false
    reference_docx: rmd_word_template_journ_guide.docx
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
---

# Acknowledgements

We thank our funders: Rohini Nilekani Philanthropies, Duleep Matthai Nature Conservation Trust, and Cholamandalam Investments and Finance Co. Ltd. We also express sincere gratitude to all eBirders who help generate and sustain this valuable scientific resource by contributing observations, and to all eBird reviewers who volunteer their time for the crucial process of maintaining data quality. We thank Praveen J, Priti Bangal and Suhel Quader for their comments that helped improve the manuscript.

# Conflict of interest

The authors declare that they have no conflicting financial or personal interests that could have influenced this study.

# Supplementary Online Material (SOM)

More details about the methodology, analyses and results are available online in supplementary materials.
